#!/usr/bin/env python3
"""
Secure Email Setup Script
Guides you through setting up Gmail authentication for the newsletter system
"""

import json
import getpass
import os
from pathlib import Path

def setup_gmail_credentials():
    print("🔐 Gmail Authentication Setup")
    print("=" * 50)
    print()
    print("To send emails, you need to set up Gmail App Password authentication.")
    print("This is more secure than using your regular password.")
    print()
    
    # Step 1: Check if 2FA is enabled
    print("Step 1: Enable 2-Factor Authentication")
    print("- Go to your Google Account settings")
    print("- Security → 2-Step Verification")
    print("- Enable it if not already enabled")
    print()
    
    input("Press Enter when you've enabled 2FA...")
    
    # Step 2: Generate App Password
    print("Step 2: Generate App Password")
    print("- Go to Google Account → Security → 2-Step Verification")
    print("- Click 'App passwords' (at the bottom)")
    print("- Select 'Mail' and 'Other (Custom name)'")
    print("- Name it 'AI Newsletter Generator'")
    print("- Copy the 16-character password")
    print()
    
    # Get user input
    email = input("Enter your Gmail address: ").strip()
    
    if not email.endswith("@gmail.com"):
        print("❌ Please enter a valid Gmail address")
        return False
    
    print("\nEnter your Gmail App Password (16 characters):")
    app_password = getpass.getpass("App Password: ").strip()
    
    if len(app_password) != 16:
        print("❌ App Password should be 16 characters long")
        return False
    
    # Update email config
    config_path = "config/email_config.json"
    
    try:
        with open(config_path, 'r') as f:
            config = json.load(f)
        
        config["sender_email"] = email
        config["sender_password"] = app_password
        config["reply_to"] = email
        
        with open(config_path, 'w') as f:
            json.dump(config, f, indent=2)
        
        print(f"✅ Email configuration updated successfully!")
        print(f"📧 Sender email: {email}")
        print()
        
        return True
        
    except Exception as e:
        print(f"❌ Error updating config: {e}")
        return False

def test_email_connection():
    print("🧪 Testing Email Connection")
    print("=" * 30)
    
    try:
        from src.email_distributor import EmailDistributor
        
        distributor = EmailDistributor()
        
        # Test with a simple email
        print("Sending test email...")
        
        # Create a simple test newsletter
        html_content = """
        <html>
        <body>
            <h1>🎉 AI Newsletter Generator Test</h1>
            <p>This is a test email to verify your Gmail configuration is working correctly.</p>
            <p>If you received this email, your setup is successful!</p>
            <hr>
            <p style="font-size: 12px; color: #666;">
            Generated by AI Newsletter Generator<br>
            Test sent on {date}
            </p>
        </body>
        </html>
        """.format(date=datetime.now().strftime("%B %d, %Y"))
        
        text_content = """
AI Newsletter Generator Test

This is a test email to verify your Gmail configuration is working correctly.

If you received this email, your setup is successful!

---
Generated by AI Newsletter Generator
Test sent on {date}
        """.format(date=datetime.now().strftime("%B %d, %Y"))
        
        # Get the email from config
        with open("config/email_config.json", 'r') as f:
            config = json.load(f)
        
        test_email = config["sender_email"]
        
        # Add test subscriber
        distributor.add_subscriber(test_email, "Test User")
        
        # Send test email
        results = distributor.send_newsletter(
            html_content, 
            text_content, 
            "Test Newsletter",
            "test_connection"
        )
        
        if results.get("success", False):
            print("✅ Test email sent successfully!")
            print(f"📧 Check your inbox: {test_email}")
            return True
        else:
            print(f"❌ Test email failed: {results.get('error', 'Unknown error')}")
            return False
            
    except Exception as e:
        print(f"❌ Connection test failed: {e}")
        return False

def main():
    print("📧 AI Newsletter Email Setup")
    print("=" * 40)
    print()
    
    # Check if config exists
    config_path = "config/email_config.json"
    if not Path(config_path).exists():
        print("❌ Email config file not found!")
        return
    
    # Setup credentials
    if setup_gmail_credentials():
        print("✅ Credentials configured successfully!")
        print()
        
        # Test connection
        if test_email_connection():
            print("🎉 Email setup complete!")
            print()
            print("Next steps:")
            print("1. Run: python main.py --generate")
            print("2. Check your email for the newsletter")
            print("3. Add more subscribers: python email_demo.py")
        else:
            print("❌ Email test failed. Please check your credentials.")
    else:
        print("❌ Setup failed. Please try again.")

if __name__ == "__main__":
    from datetime import datetime
    main() 