"""
AI Newsletter Email Distributor
Handles email distribution of generated newsletters to subscribers
"""

import os
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from typing import List, Dict, Any, Optional
from datetime import datetime
import json
import sqlite3
from pathlib import Path
from rich.console import Console
from rich.table import Table
from rich.progress import track

console = Console()

class EmailDistributor:
    """Handles email distribution of newsletters"""
    
    def __init__(self, config_path: str = "config/email_config.json"):
        self.config = self._load_config(config_path)
        self.db_path = "data/subscribers.db"
        self._init_database()
    
    def _load_config(self, config_path: str) -> Dict[str, Any]:
        """Load email configuration"""
        try:
            with open(config_path, 'r') as f:
                return json.load(f)
        except FileNotFoundError:
            console.print(f"[yellow]Email config not found. Using environment variables.[/yellow]")
            return self._get_default_config()
    
    def _get_default_config(self) -> Dict[str, Any]:
        """Default email configuration from environment variables"""
        return {
            "smtp_server": os.getenv("SMTP_SERVER", "smtp.gmail.com"),
            "smtp_port": int(os.getenv("SMTP_PORT", "587")),
            "sender_email": os.getenv("SENDER_EMAIL", ""),
            "sender_password": os.getenv("SENDER_PASSWORD", ""),
            "sender_name": os.getenv("SENDER_NAME", "AI Newsletter Generator"),
            "reply_to": os.getenv("REPLY_TO", ""),
            "subject_template": "The {theme} Weekly - {date}",
            "footer_template": """
            <hr>
            <p style="font-size: 12px; color: #666;">
            This newsletter was generated by AI technology.<br>
            To unsubscribe, click <a href="{unsubscribe_url}">here</a>.<br>
            Generated on {date}
            </p>
            """
        }
    
    def _init_database(self):
        """Initialize subscriber database"""
        Path("data").mkdir(exist_ok=True)
        
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS subscribers (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email TEXT UNIQUE NOT NULL,
                name TEXT,
                subscribed_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                last_sent TIMESTAMP,
                status TEXT DEFAULT 'active',
                preferences TEXT
            )
        ''')
        
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS email_logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                subscriber_id INTEGER,
                newsletter_id TEXT,
                sent_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                status TEXT,
                error_message TEXT,
                FOREIGN KEY (subscriber_id) REFERENCES subscribers (id)
            )
        ''')
        
        conn.commit()
        conn.close()
    
    def add_subscriber(self, email: str, name: str = "", preferences: Dict = None) -> bool:
        """Add a new subscriber"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            preferences_json = json.dumps(preferences) if preferences else "{}"
            
            cursor.execute('''
                INSERT OR REPLACE INTO subscribers (email, name, preferences)
                VALUES (?, ?, ?)
            ''', (email, name, preferences_json))
            
            conn.commit()
            conn.close()
            
            console.print(f"[green]✓ Added subscriber: {email}[/green]")
            return True
            
        except Exception as e:
            console.print(f"[red]✗ Failed to add subscriber: {e}[/red]")
            return False
    
    def remove_subscriber(self, email: str) -> bool:
        """Remove a subscriber"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            cursor.execute('''
                UPDATE subscribers SET status = 'unsubscribed'
                WHERE email = ?
            ''', (email,))
            
            conn.commit()
            conn.close()
            
            console.print(f"[green]✓ Unsubscribed: {email}[/green]")
            return True
            
        except Exception as e:
            console.print(f"[red]✗ Failed to unsubscribe: {e}[/red]")
            return False
    
    def get_active_subscribers(self) -> List[Dict[str, Any]]:
        """Get all active subscribers"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute('''
            SELECT id, email, name, preferences
            FROM subscribers
            WHERE status = 'active'
        ''')
        
        subscribers = []
        for row in cursor.fetchall():
            subscribers.append({
                'id': row[0],
                'email': row[1],
                'name': row[2],
                'preferences': json.loads(row[3]) if row[3] else {}
            })
        
        conn.close()
        return subscribers
    
    def send_newsletter(self, newsletter_html: str, newsletter_text: str, 
                       theme: str = "Technology & Innovation", 
                       newsletter_id: str = None) -> Dict[str, Any]:
        """Send newsletter to all active subscribers"""
        if not self.config["sender_email"] or not self.config["sender_password"]:
            console.print("[red]✗ Email credentials not configured[/red]")
            return {"success": False, "error": "Email credentials not configured"}
        
        subscribers = self.get_active_subscribers()
        if not subscribers:
            console.print("[yellow]No active subscribers found[/yellow]")
            return {"success": False, "error": "No active subscribers"}
        
        console.print(f"[blue]Sending newsletter to {len(subscribers)} subscribers...[/blue]")
        
        results = {
            "total_subscribers": len(subscribers),
            "sent_successfully": 0,
            "failed": 0,
            "errors": []
        }
        
        # Create email content
        subject = self.config["subject_template"].format(
            theme=theme,
            date=datetime.now().strftime("%B %d, %Y")
        )
        
        for subscriber in track(subscribers, description="Sending emails"):
            try:
                success = self._send_single_email(
                    subscriber, subject, newsletter_html, newsletter_text, newsletter_id
                )
                
                if success:
                    results["sent_successfully"] += 1
                else:
                    results["failed"] += 1
                    
            except Exception as e:
                results["failed"] += 1
                results["errors"].append(f"{subscriber['email']}: {str(e)}")
                console.print(f"[red]Failed to send to {subscriber['email']}: {e}[/red]")
        
        # Log results
        self._log_email_results(results, newsletter_id)
        
        # Show summary
        self._show_email_summary(results)
        
        return results
    
    def _send_single_email(self, subscriber: Dict, subject: str, 
                          html_content: str, text_content: str, 
                          newsletter_id: str) -> bool:
        """Send email to a single subscriber"""
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = f"{self.config['sender_name']} <{self.config['sender_email']}>"
            msg['To'] = subscriber['email']
            
            if self.config.get('reply_to'):
                msg['Reply-To'] = self.config['reply_to']
            
            # Add unsubscribe link
            unsubscribe_url = f"http://example.com/unsubscribe?email={subscriber['email']}"
            footer = self.config["footer_template"].format(
                unsubscribe_url=unsubscribe_url,
                date=datetime.now().strftime("%B %d, %Y")
            )
            
            # Attach HTML content
            html_with_footer = html_content + footer
            html_part = MIMEText(html_with_footer, 'html')
            msg.attach(html_part)
            
            # Attach text content
            text_with_footer = text_content + "\n\n" + footer.replace('<br>', '\n').replace('<hr>', '---')
            text_part = MIMEText(text_with_footer, 'plain')
            msg.attach(text_part)
            
            # Send email
            context = ssl.create_default_context()
            
            with smtplib.SMTP(self.config["smtp_server"], self.config["smtp_port"]) as server:
                server.starttls(context=context)
                server.login(self.config["sender_email"], self.config["sender_password"])
                server.send_message(msg)
            
            # Update last sent timestamp
            self._update_last_sent(subscriber['id'], newsletter_id)
            
            return True
            
        except Exception as e:
            self._log_email_error(subscriber['id'], newsletter_id, str(e))
            return False
    
    def _update_last_sent(self, subscriber_id: int, newsletter_id: str):
        """Update last sent timestamp for subscriber"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute('''
            UPDATE subscribers 
            SET last_sent = CURRENT_TIMESTAMP
            WHERE id = ?
        ''', (subscriber_id,))
        
        conn.commit()
        conn.close()
    
    def _log_email_error(self, subscriber_id: int, newsletter_id: str, error_message: str):
        """Log email sending error"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute('''
            INSERT INTO email_logs (subscriber_id, newsletter_id, status, error_message)
            VALUES (?, ?, ?, ?)
        ''', (subscriber_id, newsletter_id, 'failed', error_message))
        
        conn.commit()
        conn.close()
    
    def _log_email_results(self, results: Dict, newsletter_id: str):
        """Log overall email sending results"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        # Log successful sends
        if results["sent_successfully"] > 0:
            cursor.execute('''
                INSERT INTO email_logs (newsletter_id, status)
                VALUES (?, ?)
            ''', (newsletter_id, f"sent_successfully_{results['sent_successfully']}"))
        
        # Log failures
        if results["failed"] > 0:
            cursor.execute('''
                INSERT INTO email_logs (newsletter_id, status, error_message)
                VALUES (?, ?, ?)
            ''', (newsletter_id, f"failed_{results['failed']}", str(results["errors"])))
        
        conn.commit()
        conn.close()
    
    def _show_email_summary(self, results: Dict):
        """Display email sending summary"""
        table = Table(title="Email Distribution Summary")
        table.add_column("Metric", style="cyan")
        table.add_column("Value", style="magenta")
        
        table.add_row("Total Subscribers", str(results["total_subscribers"]))
        table.add_row("Sent Successfully", str(results["sent_successfully"]))
        table.add_row("Failed", str(results["failed"]))
        table.add_row("Success Rate", f"{(results['sent_successfully']/results['total_subscribers']*100):.1f}%")
        
        console.print(table)
        
        if results["errors"]:
            console.print("\n[yellow]Errors:[/yellow]")
            for error in results["errors"][:5]:  # Show first 5 errors
                console.print(f"• {error}")
    
    def get_subscriber_stats(self) -> Dict[str, Any]:
        """Get subscriber statistics"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        # Total subscribers
        cursor.execute('SELECT COUNT(*) FROM subscribers')
        total = cursor.fetchone()[0]
        
        # Active subscribers
        cursor.execute('SELECT COUNT(*) FROM subscribers WHERE status = "active"')
        active = cursor.fetchone()[0]
        
        # Recent subscribers (last 30 days)
        cursor.execute('''
            SELECT COUNT(*) FROM subscribers 
            WHERE subscribed_date >= datetime('now', '-30 days')
        ''')
        recent = cursor.fetchone()[0]
        
        # Email sending stats
        cursor.execute('SELECT COUNT(*) FROM email_logs WHERE status LIKE "sent_successfully%"')
        emails_sent = cursor.fetchone()[0]
        
        conn.close()
        
        return {
            "total_subscribers": total,
            "active_subscribers": active,
            "recent_subscribers": recent,
            "emails_sent": emails_sent
        }
    
    def export_subscribers(self, filename: str = "subscribers_export.csv"):
        """Export subscribers to CSV"""
        import csv
        
        subscribers = self.get_active_subscribers()
        
        with open(filename, 'w', newline='') as csvfile:
            fieldnames = ['email', 'name', 'subscribed_date', 'preferences']
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            
            writer.writeheader()
            for subscriber in subscribers:
                writer.writerow({
                    'email': subscriber['email'],
                    'name': subscriber['name'],
                    'subscribed_date': datetime.now().strftime('%Y-%m-%d'),
                    'preferences': json.dumps(subscriber['preferences'])
                })
        
        console.print(f"[green]✓ Exported {len(subscribers)} subscribers to {filename}[/green]")

if __name__ == "__main__":
    # Example usage
    distributor = EmailDistributor()
    
    # Add some test subscribers
    distributor.add_subscriber("test1@example.com", "Test User 1")
    distributor.add_subscriber("test2@example.com", "Test User 2")
    
    # Get stats
    stats = distributor.get_subscriber_stats()
    console.print(f"Subscriber stats: {stats}")
    
    # Export subscribers
    distributor.export_subscribers() 